server:
  port: 80

  datasource: 
    url: jdbc:mysql://127.0.0.1:3306/c71-s3-tmlzy-property
    username: root
    password: muhao
    driver-class-name: com.mysql.jdbc.Driver
    
logging: 
  level: 
    com: 
      yc: debug